#!/bin/bash
#
# chkconfig: 345 90 12
# description: Synergy/DE License Manager service
# process: synd
#
# Set the path to your version of synergy here
SYNDIR=/var/opt/synergyde/10.1.1b
# Get function from functions library
. /etc/init.d/functions
# Start the service Synergy/DE License Manager
start() {
        echo -n "Starting Synergy/DE License Manager service: "
        $SYNDIR/lm/synd & > /dev/null 2>1
        ### Create the lock file ###
        touch /var/lock/subsys/synd
        success $"Synergy/DE License Manager service startup"
        echo
}
# Restart the service Synergy/DE License Manager
stop() {
        echo -n "Stopping Synergy/DE License Manager service: "
        $SYNDIR/lm/synd -q > /dev/null 2>1
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/synd
        success $"Synergy/DE License Manager service stopped"
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status synd
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
